# Generated by Django 4.2.3 on 2023-09-12 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='Age',
        ),
        migrations.RemoveField(
            model_name='person',
            name='track',
        ),
    ]
